# Generated by Django 4.2 on 2024-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='decription',
            field=models.TextField(max_length=200),
        ),
    ]
