# Generated by Django 4.2 on 2024-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_orders_order_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=500.0),
            preserve_default=False,
        ),
    ]
