# Generated by Django 4.2 on 2024-03-22 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
