# Generated by Django 4.2 on 2024-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cart_price_remove_cart_title_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
