# Generated by Django 4.2 on 2024-03-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_price_cart_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
